const $ = (id) => document.getElementById(id);
const state = { mode:'address', suggestionToken:0, analysisToken:0, suggestions:[], selected:null, listing:null };
const cache = { proxy:new Map(), epcPostcode:new Map(), epcDetail:new Map(), landRegistry:new Map(), rightmovePostcode:new Map() };

function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));}
function money(value){const n=Number(value);return Number.isFinite(n)?new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(n):'—';}
function dateShort(value){const d=new Date(`${String(value||'').slice(0,10)}T00:00:00Z`);return Number.isFinite(d.getTime())?d.toLocaleDateString('en-GB',{month:'short',year:'numeric'}):String(value||'');}
function setStatus(text,tone=''){const el=$('appStatus');if(!el)return;el.textContent=text;el.className=`status-pill${tone?` ${tone}`:''}`;}
function setLoading(show,title='Checking property…',text='Finding the address and nearby evidence.'){ $('loadingCard')?.classList.toggle('hidden',!show); if($('loadingTitle'))$('loadingTitle').textContent=title;if($('loadingText'))$('loadingText').textContent=text; }
function showError(message){const card=$('errorCard');if(!card)return;card.textContent=message||'Something went wrong.';card.classList.remove('hidden');}
function clearError(){$('errorCard')?.classList.add('hidden');}
function resetResults(){$('results')?.classList.add('hidden');$('marketCard')?.classList.add('hidden');if($('comparables'))$('comparables').innerHTML='';if($('marketListings'))$('marketListings').innerHTML='';}

async function proxyResponse(target,accept='*/*',ttl=0){const key=`${accept}|${target}`,hit=cache.proxy.get(key);if(ttl&&hit&&Date.now()-hit.time<ttl)return hit.response.clone();const url=new URL('/api/proxy',location.origin);url.searchParams.set('url',target);url.searchParams.set('accept',accept);const response=await fetch(url.toString(),{headers:{Accept:accept}});if(!response.ok){let reason=`Request failed (${response.status})`;try{reason=(await response.json())?.error||reason;}catch(_){}throw new Error(reason);}if(ttl)cache.proxy.set(key,{time:Date.now(),response:response.clone()});return response;}
async function proxyText(target,ttl=0){return (await proxyResponse(target,'text/html,application/xhtml+xml,*/*;q=0.8',ttl)).text();}
async function proxyJson(target,ttl=0){return (await proxyResponse(target,'application/json,*/*;q=0.8',ttl)).json();}

function normalisePostcode(value){const compact=String(value||'').toUpperCase().replace(/\s+/g,'').trim(),m=compact.match(/^([A-Z]{1,2}\d[A-Z\d]?)(\d[A-Z]{2})$/);return m?`${m[1]} ${m[2]}`:'';}
function parseAddressQuery(query){const clean=String(query||'').replace(/\s+/g,' ').trim();const postcodeMatch=clean.match(/\b[A-Z]{1,2}\d[A-Z\d]?\s*\d[A-Z]{2}\b/i);const postcode=postcodeMatch?normalisePostcode(postcodeMatch[0]):'';const withoutPostcode=postcodeMatch?clean.replace(postcodeMatch[0],'').replace(/\s*,\s*$/,'').trim():clean;const parts=withoutPostcode.split(',').map(x=>x.trim()).filter(Boolean),first=parts[0]||withoutPostcode;const flatMatch=first.match(/^(flat|apartment|unit)\s+([a-z0-9-]+)\s*,?\s*/i),afterFlat=flatMatch?first.slice(flatMatch[0].length).trim():first;const numberMatch=afterFlat.match(/^(\d+[a-z]?(?:\s*[-/]\s*\d+[a-z]?)?)\b\s*(.*)$/i);const houseNumber=numberMatch?numberMatch[1].replace(/\s+/g,''):'',road=numberMatch?String(numberMatch[2]||'').trim():'';const flatLabel=flatMatch?`${flatMatch[1][0].toUpperCase()}${flatMatch[1].slice(1).toLowerCase()} ${flatMatch[2]}`:'',flatNumber=flatMatch?String(flatMatch[2]||'').replace(/\s+/g,''):'';return {clean,postcode,houseNumber,flatNumber,lookupNumber:flatNumber||houseNumber,road,locality:parts.slice(1).join(', '),premiseLabel:[flatLabel,houseNumber].filter(Boolean).join(', ')};}
function normaliseRoad(value){return String(value||'').toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();}
function manualPostcode(row){return normalisePostcode(row?.address?.postcode||String(row?.display_name||'').match(/\b[A-Z]{1,2}\d[A-Z\d]?\s*\d[A-Z]{2}\b/i)?.[0]||'');}
function displayName(row){if(row?._exactDisplay)return String(row._exactDisplay).trim();const a=row?.address||{},road=a.road||a.pedestrian||a.residential||a.footway||'',premise=[row?._premiseLabel||a.house_number||'',road].filter(Boolean).join(' '),locality=a.city||a.town||a.village||a.hamlet||a.suburb||a.county||'',postcode=manualPostcode(row),compact=[premise,locality,postcode].filter(Boolean).join(', ');if(compact&&premise)return compact;return String(row?.display_name||'').replace(/,\s*(United Kingdom|UK)\s*$/i,'').replace(/\s+/g,' ').trim();}
function titleCaseAddress(value){const raw=String(value||'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim();const pc=raw.match(/\b[A-Z]{1,2}\d[A-Z\d]?\s*\d[A-Z]{2}\b/i)?.[0]||'',postcode=normalisePostcode(pc),body=pc?raw.replace(pc,'').replace(/[\s,]+$/,''):raw;const formatted=body.split(',').map(part=>part.trim().split(/\s+/).map(word=>/^\d+[a-z]?$/i.test(word)?word.toUpperCase():word.split(/([-'’])/).map(p=>/[-'’]/.test(p)?p:p.charAt(0).toUpperCase()+p.slice(1).toLowerCase()).join('')).join(' ')).filter(Boolean).join(', ');return [formatted,postcode].filter(Boolean).join(', ');}
function addressNumberTokens(address){const value=String(address||'').toUpperCase().replace(/\s+/g,' ').trim(),tokens=new Set();const unit=value.match(/(?:^|,\s*)(?:FLAT|APARTMENT|UNIT)\s+([0-9]+[A-Z]?)(?=\b|,)/i),leading=value.match(/^\s*([0-9]+[A-Z]?)(?=\b|,)/i);if(unit?.[1])tokens.add(unit[1].replace(/\s+/g,''));if(leading?.[1])tokens.add(leading[1].replace(/\s+/g,''));return tokens;}
function roadMatchesRow(row,parsed){if(!parsed?.road)return true;const a=row?.address||{},actual=normaliseRoad(a.road||a.pedestrian||a.residential||a.footway||''),expected=normaliseRoad(parsed.road);return Boolean(actual&&expected&&(actual===expected||actual.includes(expected)||expected.includes(actual)));}
function enhanceAddressRow(row,parsed){const next={...row,address:{...(row.address||{})}},actualHouse=String(next.address.house_number||'').toUpperCase().replace(/\s+/g,''),wanted=String(parsed?.houseNumber||'').toUpperCase().replace(/\s+/g,''),matchesRoad=roadMatchesRow(next,parsed),group=String(next.address.house_number||'').split(/[,;]/).map(x=>x.trim().toUpperCase()).includes(wanted);if(wanted&&matchesRoad&&(!actualHouse||group)){next.address.house_number=parsed.houseNumber;next._premiseLabel=parsed.premiseLabel||parsed.houseNumber;}let score=0;if(wanted&&String(next.address.house_number||'').toUpperCase().replace(/\s+/g,'')===wanted)score+=100;if(matchesRoad&&parsed?.road)score+=35;if(parsed?.postcode&&manualPostcode(next).replace(/\s+/g,'')===parsed.postcode.replace(/\s+/g,''))score+=45;score+=Math.min(10,Math.max(0,Number(next.importance||0)*10));next._score=score;return next;}
async function nominatim(params,limit=7){const url=new URL('https://nominatim.openstreetmap.org/search');url.searchParams.set('format','jsonv2');url.searchParams.set('addressdetails','1');url.searchParams.set('countrycodes','gb');url.searchParams.set('limit',String(limit));Object.entries(params).forEach(([k,v])=>{if(v)url.searchParams.set(k,v);});const rows=await proxyJson(url.toString(),60000);return Array.isArray(rows)?rows:[];}
function epcSearchUrl(postcode){return `https://find-energy-certificate.service.gov.uk/find-a-certificate/search-by-postcode?postcode=${encodeURIComponent(postcode)}`;}
function parseEpcAddressRows(html,postcode){const doc=new DOMParser().parseFromString(html,'text/html'),seen=new Set(),rows=[];doc.querySelectorAll('a[href*="/energy-certificate/"]').forEach(link=>{const href=String(link.getAttribute('href')||'').trim(),address=titleCaseAddress(link.textContent||'');if(!href||!address||seen.has(href))return;seen.add(href);rows.push({href,address,postcode});});const next=doc.querySelector('a[rel="next"], .govuk-pagination__next a, a.govuk-link[aria-label*="next" i]')?.getAttribute('href')||'';return {rows,next};}
async function epcPostcodeRows(postcode){postcode=normalisePostcode(postcode);if(!postcode)return[];const cached=cache.epcPostcode.get(postcode);if(cached&&Date.now()-cached.time<600000)return cached.rows;let url=epcSearchUrl(postcode),all=[],seen=new Set();for(let page=0;page<5&&url;page++){const parsed=parseEpcAddressRows(await proxyText(url,600000),postcode);for(const row of parsed.rows)if(!seen.has(row.href)){seen.add(row.href);all.push(row);}url=parsed.next?new URL(parsed.next,'https://find-energy-certificate.service.gov.uk').toString():'';}cache.epcPostcode.set(postcode,{time:Date.now(),rows:all});return all;}
async function exactNumberPostcodeAddresses(parsed,limit=7){if(!parsed.lookupNumber||!parsed.postcode)return[];const wanted=String(parsed.lookupNumber).toUpperCase(),rows=(await epcPostcodeRows(parsed.postcode)).filter(r=>addressNumberTokens(r.address).has(wanted));if(!rows.length)return[];let centroid=null;try{centroid=(await nominatim({postalcode:parsed.postcode},1))[0]||null;}catch(_){}return rows.slice(0,limit).map((r,i)=>({lat:Number(centroid?.lat)||0,lon:Number(centroid?.lon)||0,display_name:r.address,address:{...(centroid?.address||{}),house_number:parsed.lookupNumber,postcode:parsed.postcode},importance:1-i*.01,_exactDisplay:r.address,_exactEpcHref:r.href,_premiseLabel:parsed.premiseLabel||parsed.lookupNumber,_score:250-i}));}
async function findAddresses(query,limit=7,thorough=false){const q=String(query||'').trim();if(q.length<3)return[];const parsed=parseAddressQuery(q);if(parsed.lookupNumber&&parsed.postcode&&!parsed.road){try{const exact=await exactNumberPostcodeAddresses(parsed,limit);if(exact.length)return exact;}catch(_){}}let raw=[];if(parsed.houseNumber&&parsed.road)raw=await nominatim({street:`${parsed.houseNumber} ${parsed.road}`,city:parsed.locality,postalcode:parsed.postcode},limit);else raw=await nominatim({q},limit);if(thorough&&!raw.length&&parsed.houseNumber&&parsed.road)raw=await nominatim({q},limit);const seen=new Set();return raw.map(row=>({lat:Number(row.lat),lon:Number(row.lon),display_name:String(row.display_name||''),address:row.address||{},importance:Number(row.importance||0)})).filter(r=>Number.isFinite(r.lat)&&Number.isFinite(r.lon)).map(r=>enhanceAddressRow(r,parsed)).filter(r=>{const k=`${r.lat.toFixed(6)},${r.lon.toFixed(6)}|${displayName(r).toLowerCase()}`;if(seen.has(k))return false;seen.add(k);return true;}).sort((a,b)=>(b._score||0)-(a._score||0)).slice(0,limit);}

function epcNormalise(value){return String(value||'').toLowerCase().replace(/\b(united kingdom|uk)\b/g,'').replace(/&/g,'and').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();}
function epcPremise(value){const clean=String(value||'').trim(),flat=clean.match(/^(?:flat|apartment|unit)\s+([a-z0-9-]+)/i);if(flat)return `flat ${flat[1].toLowerCase()}`;return clean.match(/^(\d+[a-z]?)(?:\b|,)/i)?.[1]?.toLowerCase()||'';}
function scoreEpcAddress(candidateAddress,manual){const candidate=epcNormalise(candidateAddress),selected=epcNormalise(displayName(manual));if(!candidate||!selected)return-999;const postcode=epcNormalise(manualPostcode(manual)),expectedPremise=String(manual?._epcPremise||manual?.address?.house_number||epcPremise(displayName(manual))).toLowerCase().trim(),candidatePremise=epcPremise(candidateAddress);if(expectedPremise&&candidatePremise&&expectedPremise!==candidatePremise)return-999;let score=0;if(postcode&&candidate.includes(postcode))score+=50;if(expectedPremise&&candidatePremise===expectedPremise)score+=70;const road=manual?.address?.road||manual?.address?.pedestrian||manual?.address?.residential||manual?.address?.footway||'';for(const token of epcNormalise(road).split(' ').filter(t=>t.length>2))if(candidate.includes(token))score+=12;const selectedTokens=new Set(selected.split(' ').filter(t=>t.length>2)),candidateTokens=new Set(candidate.split(' '));let overlap=0;selectedTokens.forEach(t=>{if(candidateTokens.has(t))overlap++;});return score+Math.min(35,overlap*5);}
function parseEpcDetails(html){const doc=new DOMParser().parseFromString(html,'text/html'),details={};const textFor=patterns=>{for(const dt of doc.querySelectorAll('dt')){const label=String(dt.textContent||'').replace(/\s+/g,' ').trim();if(patterns.some(p=>p.test(label)))return String(dt.nextElementSibling?.textContent||'').replace(/\s+/g,' ').trim();}return'';};const areaText=textFor([/total\s+floor\s+area/i])||String(doc.body?.innerText||'').match(/total\s+floor\s+area.{0,80}?([\d,.]+)\s*(?:square\s+metres?|sq\.?\s*m|sqm|m²|m2)/i)?.[0]||'',sqm=Number(String(areaText).match(/([\d,.]+)\s*(?:square\s+metres?|sq\.?\s*m|sqm|m²|m2)/i)?.[1]?.replace(/,/g,''));if(Number.isFinite(sqm)&&sqm>=14&&sqm<=3000){details.sqm=Math.round(sqm*10)/10;details.sqft=Math.round(sqm*10.7639);}details.propertyType=textFor([/^property\s+type$/i]);details.builtForm=textFor([/^built\s+form$/i]);details.tenure=textFor([/^tenure$/i]);const body=String(doc.body?.innerText||doc.body?.textContent||'').replace(/\s+/g,' '),rating=textFor([/^current\s+energy\s+(?:efficiency\s+)?rating$/i,/^energy\s+rating$/i]).match(/\b([A-G])\b/i)?.[1]||body.slice(0,2200).match(/current\s+energy(?:\s+efficiency)?\s+rating.{0,35}?\b([A-G])\b/i)?.[1]||body.slice(0,2200).match(/energy\s+rating\s+([A-G])\s+valid\s+until/i)?.[1]||'';details.currentEnergyRating=String(rating).toUpperCase();const hab=Number.parseInt(textFor([/^number\s+of\s+habitable\s+rooms$/i,/^habitable\s+rooms$/i]),10);details.habitableRooms=Number.isFinite(hab)&&hab>0?hab:null;return details;}
async function epcDetails(href){if(!href)return null;const url=new URL(href,'https://find-energy-certificate.service.gov.uk').toString(),hit=cache.epcDetail.get(url);if(hit&&Date.now()-hit.time<1800000)return hit.details;const details=parseEpcDetails(await proxyText(url,1800000));details.certificateUrl=url;cache.epcDetail.set(url,{time:Date.now(),details});return details;}
async function loadEpc(manual,listing=null){if(listing?.epcUrl){try{return await epcDetails(listing.epcUrl);}catch(_){}}const postcode=manualPostcode(manual)||listing?.postcode||'';if(!postcode)return listing?.epcRating?{currentEnergyRating:listing.epcRating}:null;let match=manual?._exactEpcHref?{href:manual._exactEpcHref,score:999}:null;if(!match){const rows=await epcPostcodeRows(postcode),ranked=rows.map(r=>({...r,score:scoreEpcAddress(r.address,manual)})).filter(r=>r.score>0).sort((a,b)=>b.score-a.score);if(ranked[0]?.score>=70&&(!ranked[1]||ranked[1].score<ranked[0].score-8||ranked[1].address===ranked[0].address))match=ranked[0];}if(!match)return listing?.epcRating?{currentEnergyRating:listing.epcRating}:null;try{const d=await epcDetails(match.href);if(!d.currentEnergyRating&&listing?.epcRating)d.currentEnergyRating=listing.epcRating;return d;}catch(_){return listing?.epcRating?{currentEnergyRating:listing.epcRating}:null;}}

function lrValue(binding,key){return String(binding?.[key]?.value||'').trim();}
function lrRows(payload){const bindings=Array.isArray(payload?.results?.bindings)?payload.results.bindings:[];return bindings.map(b=>({transaction:lrValue(b,'transaction'),amount:Number(lrValue(b,'amount')),date:lrValue(b,'date').slice(0,10),paon:lrValue(b,'paon'),saon:lrValue(b,'saon'),street:lrValue(b,'street'),town:lrValue(b,'town'),postcode:lrValue(b,'postcode').toUpperCase(),propertyType:lrValue(b,'propertyType'),estateType:lrValue(b,'estateType')})).filter(r=>Number.isFinite(r.amount)&&r.amount>0&&r.date&&r.postcode);}
function sparqlEscape(v){return String(v||'').replace(/\\/g,'\\\\').replace(/"/g,'\\"');}
function lrSelect(extra,limit=250){return `PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>\nPREFIX lrppi: <http://landregistry.data.gov.uk/def/ppi/>\nPREFIX lrcommon: <http://landregistry.data.gov.uk/def/common/>\nSELECT DISTINCT ?transaction ?amount ?date ?paon ?saon ?street ?town ?postcode ?propertyType ?estateType WHERE {\n?transaction lrppi:pricePaid ?amount ; lrppi:transactionDate ?date ; lrppi:propertyAddress ?address .\n?address lrcommon:postcode ?postcode .\nOPTIONAL { ?address lrcommon:paon ?paon } OPTIONAL { ?address lrcommon:saon ?saon } OPTIONAL { ?address lrcommon:street ?street } OPTIONAL { ?address lrcommon:town ?town }\nOPTIONAL { ?transaction lrppi:propertyType ?propertyType } OPTIONAL { ?transaction lrppi:estateType ?estateType }\n${extra}\n}\nORDER BY DESC(?date)\nLIMIT ${limit}`;}
async function lrQuery(query,key){const hit=cache.landRegistry.get(key);if(hit&&Date.now()-hit.time<1200000)return hit.rows;const url=new URL('https://landregistry.data.gov.uk/landregistry/query');url.searchParams.set('queryLn','SPARQL');url.searchParams.set('query',query);url.searchParams.set('limit','none');url.searchParams.set('infer','true');url.searchParams.set('Accept','application/sparql-results+json');const rows=lrRows(await proxyJson(url.toString(),300000));cache.landRegistry.set(key,{time:Date.now(),rows});return rows;}
async function postcodeSales(postcode){const pc=normalisePostcode(postcode);if(!pc)return[];return lrQuery(lrSelect(`VALUES ?postcode { "${sparqlEscape(pc)}"^^xsd:string }`,250),`postcode:${pc}`);}
function postcodeSector(postcode){const c=String(postcode||'').toUpperCase().replace(/\s+/g,''),m=c.match(/^([A-Z]{1,2}\d[A-Z\d]?)(\d)[A-Z]{2}$/);return m?`${m[1]} ${m[2]}`:'';}
async function sectorSales(postcode,propertyType=''){const sector=postcodeSector(postcode);if(!sector)return[];const cutoff=new Date();cutoff.setUTCMonth(cutoff.getUTCMonth()-24);const iso=cutoff.toISOString().slice(0,10),tail=String(propertyType||'').toLowerCase(),base='http://landregistry.data.gov.uk/def/common/';let typeClause='';if(/flat|maisonette/.test(tail))typeClause=`FILTER(?propertyType = <${base}flat-maisonette>)`;else if(/terrace|semi|detached/.test(tail))typeClause=`VALUES ?propertyType { <${base}terraced> <${base}semi-detached> <${base}detached> }`;else if(/^https?:\/\//i.test(propertyType))typeClause=`FILTER(?propertyType = <${propertyType}>)`;return lrQuery(lrSelect(`?transaction lrppi:transactionCategory lrppi:standardPricePaidTransaction . FILTER(STRSTARTS(UCASE(STR(?postcode)), "${sparqlEscape(sector)}")) FILTER(?date >= "${iso}"^^xsd:date) ${typeClause}`,320),`sector:${sector}:${tail}:${iso}`);}
function lrAddress(row){return [[row?.saon,row?.paon].filter(Boolean).join(', '),row?.street,row?.town,row?.postcode].filter(Boolean).join(', ').replace(/\s+/g,' ').trim();}
function lrNorm(v){return String(v||'').toLowerCase().replace(/\b(flat|apartment|unit)\b/g,' flat ').replace(/&/g,'and').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();}
function lrMatchScore(row,manual){const selected=lrNorm(displayName(manual)),candidate=lrNorm(lrAddress(row));if(!selected||!candidate)return-999;const wn=addressNumberTokens(displayName(manual)),cn=addressNumberTokens(lrAddress(row));if(wn.size&&cn.size&&![...wn].some(n=>cn.has(n)))return-999;let s=0;if(manualPostcode(manual).replace(/\s+/g,'')===row.postcode.replace(/\s+/g,''))s+=80;if(wn.size&&cn.size)s+=90;if(selected===candidate)s+=180;const st=new Set(selected.split(' ').filter(t=>t.length>1)),ct=new Set(candidate.split(' '));let overlap=0;st.forEach(t=>{if(ct.has(t))overlap++;});return s+Math.min(120,overlap*12);}
function matchSubject(rows,manual){const ranked=(rows||[]).map(row=>({row,score:lrMatchScore(row,manual)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score),best=ranked[0];if(!best||best.score<120)return null;const key=[best.row.saon,best.row.paon,best.row.street,best.row.postcode].map(lrNorm).join('|'),history=rows.filter(r=>[r.saon,r.paon,r.street,r.postcode].map(lrNorm).join('|')===key).sort((a,b)=>String(b.date).localeCompare(String(a.date)));return {best:best.row,history};}
function uriTail(uri){return decodeURIComponent(String(uri||'').split(/[\/#]/).filter(Boolean).pop()||'').replace(/[-_]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase());}
function typeUriFromLabel(value){const text=String(value||'').toLowerCase(),base='http://landregistry.data.gov.uk/def/common/';if(/flat|apartment|maisonette/.test(text))return`${base}flat-maisonette`;if(/semi/.test(text))return`${base}semi-detached`;if(/terrace/.test(text))return`${base}terraced`;if(/detached/.test(text))return`${base}detached`;return'';}
function typeLabel(value){const text=String(value||'');if(/semi/i.test(text))return'Semi-Detached';if(/end.*terrace/i.test(text))return'End of Terrace';if(/terrace/i.test(text))return'Terraced';if(/\bdetached\b/i.test(text))return'Detached';if(/flat|apartment|maisonette/i.test(text))return'Flat/Maisonette';if(/bungalow/i.test(text))return'Bungalow';return text?uriTail(text):'';}
function estimateBedrooms(epc,listing,type){if(Number(listing?.bedrooms)>0)return{value:Number(listing.bedrooms),estimated:false};const rooms=Number(epc?.habitableRooms);if(!Number.isFinite(rooms))return{value:/flat|apartment/i.test(type)?2:3,estimated:true};let beds=rooms-2;if(/flat|apartment/i.test(type))beds=rooms-1.5;return{value:Math.max(1,Math.min(7,Math.round(beds))),estimated:true};}
function monthsAgo(dateValue){const d=new Date(`${String(dateValue||'').slice(0,10)}T00:00:00Z`);if(!Number.isFinite(d.getTime()))return999;const n=new Date();return Math.max(0,(n.getUTCFullYear()-d.getUTCFullYear())*12+n.getUTCMonth()-d.getUTCMonth());}
function roundEstimate(v){const n=Number(v);if(!Number.isFinite(n))return null;const unit=n>=1000000?10000:5000;return Math.round(n/unit)*unit;}
function weightedMedian(rows){const list=rows.filter(x=>Number.isFinite(x.value)&&x.weight>0).sort((a,b)=>a.value-b.value),total=list.reduce((s,x)=>s+x.weight,0);let run=0;for(const x of list){run+=x.weight;if(run>=total/2)return x.value;}return list.at(-1)?.value||null;}
function dedupeSales(rows){const seen=new Set();return rows.filter(r=>{const k=r.transaction||`${r.amount}|${r.date}|${r.paon}|${r.saon}|${r.postcode}`;if(seen.has(k))return false;seen.add(k);return true;});}
async function comparableEpc(row){try{const manual={display_name:lrAddress(row),address:{house_number:row.saon||row.paon||'',road:row.street||'',postcode:row.postcode}},rows=await epcPostcodeRows(row.postcode),ranked=rows.map(r=>({...r,score:scoreEpcAddress(r.address,manual)})).filter(r=>r.score>=70).sort((a,b)=>b.score-a.score);if(!ranked[0]||ranked[1]?.score>=ranked[0].score-8)return null;return await epcDetails(ranked[0].href);}catch(_){return null;}}
function rankSales(rows,manual,subjectType){const postcode=manualPostcode(manual),road=normaliseRoad(manual?.address?.road||parseAddressQuery(displayName(manual)).road);return dedupeSales(rows).map(row=>{let score=0,m=monthsAgo(row.date);score+=Math.max(0,48-m);if(row.postcode===postcode)score+=90;if(road&&normaliseRoad(row.street)===road)score+=120;const rowType=uriTail(row.propertyType).toLowerCase(),st=String(subjectType||'').toLowerCase();if(st&&rowType){if((/flat/.test(st)&&/flat/.test(rowType))||(/terrace/.test(st)&&/terrace/.test(rowType))||(/semi/.test(st)&&/semi/.test(rowType))||(/detached/.test(st)&&/detached/.test(rowType)))score+=55;else score-=35;}return{...row,_rank:score};}).sort((a,b)=>b._rank-a._rank);}

function rightmoveTypeaheadPath(postcode){return(String(postcode||'').toUpperCase().replace(/[^A-Z0-9]/g,'').match(/.{1,2}/g)||[]).join('/');}
async function rightmovePostcodeIdentifier(postcode){const path=rightmoveTypeaheadPath(postcode);if(!path)return'';try{const data=await proxyJson(`https://www.rightmove.co.uk/typeAhead/uknostreet/${path}/`,300000),rows=data?.typeAheadLocations||[],pc=String(postcode).replace(/\s+/g,'').toUpperCase(),hit=rows.find(r=>/^POSTCODE\^/i.test(String(r?.locationIdentifier||''))&&String(r?.displayName||r?.locationName||'').replace(/\s+/g,'').toUpperCase().includes(pc))||rows.find(r=>/^POSTCODE\^/i.test(String(r?.locationIdentifier||'')));return String(hit?.locationIdentifier||'');}catch(_){return'';}}
function rightmovePrice(row){for(const v of [row?.price?.amount,row?.price?.value,row?.price?.primaryPrice,row?.prices?.primaryPrice,row?.price]){const n=Number(String(v??'').replace(/[^0-9.]/g,''));if(Number.isFinite(n)&&n>50000)return n;}return null;}
async function rightmovePostcodeListings(postcode){postcode=normalisePostcode(postcode);if(!postcode)return[];const hit=cache.rightmovePostcode.get(postcode);if(hit&&Date.now()-hit.time<720000)return hit.rows;const locationIdentifier=await rightmovePostcodeIdentifier(postcode);if(!locationIdentifier)return[];const url=new URL('https://www.rightmove.co.uk/api/_search');Object.entries({locationIdentifier,numberOfPropertiesPerPage:'24',radius:'0.0',sortType:'6',index:'0',includeSSTC:'true',viewType:'LIST',channel:'BUY',areaSizeUnit:'sqft',currencyCode:'GBP',isFetching:'false'}).forEach(([k,v])=>url.searchParams.set(k,v));const data=await proxyJson(url.toString(),180000),properties=Array.isArray(data?.properties)?data.properties:[],rows=properties.map(r=>{const loc=r?.location||{},id=String(r?.id||r?.propertyId||''),u=String(r?.propertyUrl||r?.url||(id?`/properties/${id}`:''));return{id,address:String(r?.displayAddress||r?.address?.displayAddress||r?.address||'').trim(),price:rightmovePrice(r),bedrooms:Number(r?.bedrooms)||null,bathrooms:Number(r?.bathrooms)||null,propertyType:String(r?.propertySubType||r?.propertyTypeFullDescription||r?.propertyType||''),lat:Number(loc.latitude??r?.latitude)||null,lon:Number(loc.longitude??r?.longitude)||null,url:u?new URL(u,'https://www.rightmove.co.uk').toString():''};}).filter(r=>r.price);cache.rightmovePostcode.set(postcode,{time:Date.now(),rows});return rows;}

async function buildEstimate(manual,subject,epc,listing,postcodeRows){const postcode=manualPostcode(manual),subjectTypeUri=subject?.best?.propertyType||typeUriFromLabel(listing?.propertyType||epc?.builtForm||epc?.propertyType),subjectType=typeLabel(subjectTypeUri||listing?.propertyType||epc?.builtForm||epc?.propertyType),subjectSqft=Number(listing?.squareFootage?.sqft||epc?.sqft)||null,beds=estimateBedrooms(epc,listing,subjectType),sector=await sectorSales(postcode,subjectTypeUri||subjectType).catch(()=>[]),ranked=rankSales([...postcodeRows,...sector],manual,subjectType).filter(r=>monthsAgo(r.date)<=30).slice(0,10),top=ranked.slice(0,6),enriched=await Promise.all(top.map(async row=>({row,details:await comparableEpc(row)}))),comps=[];for(const {row,details} of enriched){const compSqft=Number(details?.sqft)||null;let indication=Number(row.amount),sizeAdjusted=false;if(subjectSqft&&compSqft){const ratio=Math.max(.7,Math.min(1.45,subjectSqft/compSqft));indication=row.amount*ratio;sizeAdjusted=true;}let weight=1,m=monthsAgo(row.date);weight*=Math.max(.45,1.8-m/20);if(row.postcode===postcode)weight*=1.8;if(normaliseRoad(row.street)===normaliseRoad(manual?.address?.road||parseAddressQuery(displayName(manual)).road))weight*=1.7;if(sizeAdjusted)weight*=1.35;comps.push({...row,sqft:compSqft,implied:indication,weight,sizeAdjusted});}if(comps.length<3)for(const row of ranked.slice(comps.length,8))comps.push({...row,sqft:null,implied:Number(row.amount),weight:.55,sizeAdjusted:false});let midpoint=weightedMedian(comps.map(c=>({value:c.implied,weight:c.weight})));if(!midpoint&&subject?.history?.[0]){const latest=subject.history[0],years=Math.min(20,monthsAgo(latest.date)/12);midpoint=Number(latest.amount)*Math.pow(1.045,years);}if(!Number.isFinite(midpoint)||midpoint<50000)return{reliable:false,comps};const currentListings=await rightmovePostcodeListings(postcode).catch(()=>[]),marketPrices=currentListings.map(x=>Number(x.price)).filter(n=>Number.isFinite(n)&&n>50000).sort((a,b)=>a-b),marketMedian=marketPrices.length?marketPrices[Math.floor(marketPrices.length/2)]:null,exactAsk=Number(listing?.askingPrice)||null,anchors=[{value:midpoint,weight:5}];if(marketMedian)anchors.push({value:marketMedian*.94,weight:1.2});if(exactAsk)anchors.push({value:exactAsk*.97,weight:1});midpoint=weightedMedian(anchors);const confidence=comps.filter(c=>c.sizeAdjusted).length>=3?'High':comps.length>=4?'Medium':'Low',pad=confidence==='High'?.065:confidence==='Medium'?.09:.13;return{reliable:true,midpoint:roundEstimate(midpoint),low:roundEstimate(midpoint*(1-pad)),high:roundEstimate(midpoint*(1+pad)),confidence,comps:comps.slice(0,6),marketListings:currentListings.slice(0,8),subjectSqft,subjectBedrooms:beds.value,bedroomsEstimated:beds.estimated,propertyType:subjectType,method:comps.some(c=>c.sizeAdjusted)?'Recent sold comparables adjusted for floor area and cross-checked against current asking prices':'Recent local sale evidence cross-checked against current asking prices'};}

function manualFromListing(listing){const address=listing.exactAddress||[listing.displayAddress,listing.postcode].filter(Boolean).join(', '),parsed=parseAddressQuery(address);return{lat:Number(listing.lat)||0,lon:Number(listing.lon)||0,display_name:address,_exactDisplay:address,address:{house_number:parsed.houseNumber||parsed.flatNumber||'',road:parsed.road||'',postcode:listing.postcode||parsed.postcode||''},_epcPremise:epcPremise(address)};}
async function resolveListingManual(listing){const seed=manualFromListing(listing);if(!listing.exactAddress)return seed;try{const rows=await nominatim({q:`${listing.exactAddress}, UK`},5),pc=String(listing.postcode||'').replace(/\s+/g,''),best=rows.find(r=>normalisePostcode(r?.address?.postcode).replace(/\s+/g,'')===pc)||rows[0];if(best)return{...best,lat:Number(best.lat),lon:Number(best.lon),display_name:listing.exactAddress,_exactDisplay:listing.exactAddress,address:{...(best.address||{}),postcode:listing.postcode||best?.address?.postcode||''},_epcPremise:epcPremise(listing.exactAddress)};}catch(_){}return seed;}
async function readRightmoveLink(value){const url=new URL('/api/rightmove',location.origin);url.searchParams.set('url',value);const r=await fetch(url.toString()),data=await r.json().catch(()=>({}));if(!r.ok||!data?.ok)throw new Error(data?.error||'Could not read that Rightmove listing.');return data;}

function renderSuggestions(rows){const host=$('suggestions');if(!host)return;state.suggestions=rows||[];if(!rows?.length){host.innerHTML='';host.classList.add('hidden');return;}host.innerHTML=rows.map((r,i)=>`<button type="button" class="suggestion" data-index="${i}"><span class="pin">⌖</span><span><strong>${escapeHtml(displayName(r))}</strong><small>${escapeHtml(String(r.display_name||'').replace(/,\s*(United Kingdom|UK)\s*$/i,''))}</small></span></button>`).join('');host.classList.remove('hidden');host.querySelectorAll('[data-index]').forEach(b=>b.addEventListener('click',()=>selectAddress(rows[Number(b.dataset.index)])));}
function renderFacts(manual,epc,subject,listing,estimate){const facts=[],add=(label,value,extra='')=>{if(value!==null&&value!==undefined&&String(value)!=='')facts.push(`<div class="fact"><span>${escapeHtml(label)}</span><strong>${escapeHtml(value)}</strong>${extra}</div>`);};const address=listing?.exactAddress||displayName(manual);$('propertyAddress').textContent=address||'Property';const link=$('sourceLink');if(listing?.url){link.href=listing.url;link.classList.remove('hidden');}else link.classList.add('hidden');add('Postcode',manualPostcode(manual)||listing?.postcode||'');add('Property type',estimate?.propertyType||typeLabel(subject?.best?.propertyType||listing?.propertyType||epc?.builtForm||epc?.propertyType)||'Unknown');add('Floor area',Number(listing?.squareFootage?.sqft||epc?.sqft)>0?`${Math.round(Number(listing?.squareFootage?.sqft||epc?.sqft)).toLocaleString('en-GB')} sq ft`:'Not found');add('Bedrooms',estimate?.subjectBedrooms?`${estimate.subjectBedrooms}${estimate.bedroomsEstimated?' (estimated)':''}`:listing?.bedrooms||'');add('EPC',epc?.currentEnergyRating||listing?.epcRating||'Not found',epc?.certificateUrl?`<a class="fact-link" target="_blank" rel="noopener" href="${escapeHtml(epc.certificateUrl)}">Open</a>`:'');add('Tenure',epc?.tenure||uriTail(subject?.best?.estateType)||'');if(listing?.askingPrice)add('Current asking price',money(listing.askingPrice));if(subject?.history?.[0])add('Last registered sale',`${money(subject.history[0].amount)} · ${dateShort(subject.history[0].date)}`);$('facts').innerHTML=facts.join('');}
function renderEstimate(estimate){$('estimateMid').textContent=estimate?.reliable?money(estimate.midpoint):'Not enough evidence';$('estimateRange').textContent=estimate?.reliable?`${money(estimate.low)} – ${money(estimate.high)}`:'Try another address with a full postcode.';$('confidence').textContent=estimate?.reliable?`${estimate.confidence} confidence`:'Low data';$('confidence').className=`confidence ${String(estimate?.confidence||'low').toLowerCase()}`;$('explanation').innerHTML=estimate?.reliable?`<p>${escapeHtml(estimate.method)}.</p><p>The estimate uses ${estimate.comps.length} recent sale${estimate.comps.length===1?'':'s'}${estimate.subjectSqft?`, with a subject size of about ${Math.round(estimate.subjectSqft).toLocaleString('en-GB')} sq ft`:''}. It is an evidence-based guide, not a formal valuation.</p>`:`<p>There was not enough recent comparable evidence to calculate a sensible range without guessing.</p>`;}
function renderComparables(estimate){const rows=estimate?.comps||[];$('compCount').textContent=rows.length?`${rows.length} used`:'';$('comparables').innerHTML=rows.length?rows.map(r=>`<div class="comp"><div><strong>${escapeHtml(lrAddress(r))}</strong><span>${escapeHtml(dateShort(r.date))}${r.sqft?` · ${Math.round(r.sqft).toLocaleString('en-GB')} sq ft`:''}</span></div><div class="comp-money"><strong>${escapeHtml(money(r.amount))}</strong>${r.sizeAdjusted?`<span>Adjusted: ${escapeHtml(money(roundEstimate(r.implied)))}</span>`:''}</div></div>`).join(''):`<p class="muted">No suitable recent sold comparables found.</p>`;const market=estimate?.marketListings||[],card=$('marketCard');if(market.length){card.classList.remove('hidden');$('marketListings').innerHTML=market.map(r=>`<a class="comp market" href="${escapeHtml(r.url)}" target="_blank" rel="noopener"><div><strong>${escapeHtml(r.address||'Rightmove listing')}</strong><span>${r.bedrooms?`${r.bedrooms} bed · `:''}${escapeHtml(r.propertyType||'')}</span></div><div class="comp-money"><strong>${escapeHtml(money(r.price))}</strong></div></a>`).join('');}else card.classList.add('hidden');}

async function analyse(manual,listing=null){const token=++state.analysisToken;clearError();resetResults();setLoading(true,'Checking property…','Matching EPC, sold prices and current market evidence.');setStatus('Working','loading');try{const postcode=manualPostcode(manual)||listing?.postcode||'';if(!postcode)throw new Error('A full postcode is needed for the property search.');const [epc,postcodeRows]=await Promise.all([loadEpc(manual,listing).catch(()=>null),postcodeSales(postcode).catch(()=>[])]);if(token!==state.analysisToken)return;const subject=matchSubject(postcodeRows,manual);setLoading(true,'Building estimate…','Checking recent comparable sales and current Rightmove asking prices.');const estimate=await buildEstimate(manual,subject,epc,listing,postcodeRows);if(token!==state.analysisToken)return;renderEstimate(estimate);renderFacts(manual,epc,subject,listing,estimate);renderComparables(estimate);$('results').classList.remove('hidden');setStatus('Ready','good');}catch(error){if(token!==state.analysisToken)return;showError(error?.message||'Could not analyse this property.');setStatus('Error','bad');}finally{if(token===state.analysisToken)setLoading(false);}}
async function selectAddress(row){state.selected=row;state.listing=null;renderSuggestions([]);$('searchInput').value=displayName(row);await analyse(row,null);}
async function runSearch(){clearError();const value=String($('searchInput')?.value||'').trim();if(!value){showError(state.mode==='rightmove'?'Paste a Rightmove property link.':'Enter a property address.');return;}if(state.mode==='rightmove'){resetResults();setLoading(true,'Reading Rightmove listing…','Finding the listing address, EPC and property details.');setStatus('Working','loading');renderSuggestions([]);try{const listing=await readRightmoveLink(value);state.listing=listing;const manual=await resolveListingManual(listing);state.selected=manual;await analyse(manual,listing);}catch(error){setLoading(false);showError(error?.message||'Could not read that Rightmove link.');setStatus('Error','bad');}return;}setLoading(true,'Finding address…','Searching for the exact property.');setStatus('Working','loading');try{const rows=await findAddresses(value,7,true);setLoading(false);if(!rows.length){showError('No address found. Try the house number, road and full postcode.');setStatus('Ready');return;}if(rows.length===1){await selectAddress(rows[0]);return;}renderSuggestions(rows);setStatus('Choose address');}catch(error){setLoading(false);showError(error?.message||'Could not search addresses.');setStatus('Error','bad');}}
function setMode(mode){state.mode=mode;state.suggestionToken++;renderSuggestions([]);clearError();resetResults();document.querySelectorAll('.mode-tab').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));if(mode==='rightmove'){$('inputLabel').textContent='Rightmove property link';$('searchInput').placeholder='https://www.rightmove.co.uk/properties/…';$('searchInput').autocomplete='off';$('helperText').textContent='Paste the full Rightmove property URL. The site will try the normal address match first, then the safe EPC fallback.';}else{$('inputLabel').textContent='Property address';$('searchInput').placeholder='e.g. 8 Upton Avenue, St Albans, AL3 5EW';$('searchInput').autocomplete='street-address';$('helperText').textContent='Include the postcode where possible for the strongest match.';}$('searchInput').value='';setStatus('Ready');}

document.querySelectorAll('.mode-tab').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));
$('searchForm')?.addEventListener('submit',e=>{e.preventDefault();runSearch();});
let autocompleteTimer=null;
$('searchInput')?.addEventListener('input',()=>{clearTimeout(autocompleteTimer);if(state.mode!=='address'){renderSuggestions([]);return;}const value=$('searchInput').value.trim();if(value.length<4){renderSuggestions([]);return;}const token=++state.suggestionToken;autocompleteTimer=setTimeout(async()=>{try{const rows=await findAddresses(value,5,false);if(token===state.suggestionToken)renderSuggestions(rows);}catch(_){if(token===state.suggestionToken)renderSuggestions([]);}},300);});
document.addEventListener('click',e=>{if(!e.target.closest('.search-card'))renderSuggestions([]);});
(async()=>{try{const r=await fetch('/api/health',{cache:'no-store'});if(!r.ok)throw new Error();setStatus('Ready','good');}catch(_){setStatus('Setup needed','bad');showError('The website frontend is loaded, but its secure proxy is not running. Deploy this repository on Cloudflare Pages so Rightmove, EPC and Land Registry searches can work.');}})();
