const clean=v=>String(v||'').replace(/<script\b[\s\S]*?<\/script>/gi,' ').replace(/<style\b[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;|&#34;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&pound;|&#163;/gi,'£').replace(/\s+/g,' ').trim();
const pc=v=>{const c=String(v||'').toUpperCase().replace(/\s+/g,''),m=c.match(/^([A-Z]{1,2}\d[A-Z\d]?)(\d[A-Z]{2})$/);return m?`${m[1]} ${m[2]}`:'';};
const money=v=>{if(typeof v==='number'&&Number.isFinite(v))return v;const m=String(v||'').replace(/,/g,'').match(/(\d+(?:\.\d+)?)/);return m?Number(m[1]):null;};
const road=v=>String(v||'').toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
const parse=v=>{const s=String(v||'').replace(/\s+/g,' ').trim(),pm=s.match(/\b[A-Z]{1,2}\d[A-Z\d]?\s*\d[A-Z]{2}\b/i),postcode=pm?pc(pm[0]):'',body=(pm?s.replace(pm[0],''):s).replace(/[\s,]+$/,''),parts=body.split(',').map(x=>x.trim()).filter(Boolean),flat=parts[0]?.match(/^(?:flat|apartment|unit)\s+([a-z0-9-]+)\s*$/i);let first=parts[0]||'',i=1;if(flat&&parts[1]){first=parts[1];i=2}const n=first.match(/^(\d+[a-z]?(?:\s*[-/]\s*\d+[a-z]?)?)\b\s*(.*)$/i);return{clean:s,postcode,houseNumber:n?.[1]?.replace(/\s+/g,'')||'',lookupNumber:(flat?.[1]||n?.[1]||'').replace(/\s+/g,''),road:String(n?.[2]||first).trim(),locality:parts.slice(i).join(', ')};};
const nums=a=>{const s=String(a||'').toUpperCase(),out=new Set(),f=s.match(/(?:FLAT|APARTMENT|UNIT)\s+([0-9]+[A-Z]?)/i),l=s.match(/^\s*([0-9]+[A-Z]?)/);if(f?.[1])out.add(f[1]);if(l?.[1])out.add(l[1]);return out;};
const sameRoad=(a,b)=>{const A=road(a),t=road(b).split(' ').filter(x=>x.length>2);return!t.length||t.every(x=>A.includes(x));};
const timed=(p,ms,fallback)=>Promise.race([p,new Promise(r=>setTimeout(()=>r(fallback),ms))]);
async function cached(url,accept='*/*',ttl=300){const key=new Request(url,{headers:{Accept:accept}}),hit=await caches.default.match(key);if(hit)return hit;const r=await fetch(url,{headers:{Accept:accept,'Accept-Language':'en-GB,en;q=0.9','User-Agent':'Mozilla/5.0 (compatible; PropertyTool/3.0)'}});if(!r.ok)throw new Error(`Upstream ${r.status}`);const h=new Headers(r.headers);h.set('Cache-Control',`public, max-age=${ttl}`);const out=new Response(r.body,{status:r.status,headers:h});if(ttl)await caches.default.put(key,out.clone());return out;}
const text=(u,t=300)=>cached(u,'text/html,application/xhtml+xml,*/*;q=0.8',t).then(r=>r.text()),json=(u,t=300)=>cached(u,'application/json,*/*;q=0.8',t).then(r=>r.json());
const title=a=>{const raw=clean(a),praw=raw.match(/\b[A-Z]{1,2}\d[A-Z\d]?\s*\d[A-Z]{2}\b/i)?.[0]||'',p=pc(praw),body=(praw?raw.replace(praw,''):raw).replace(/[\s,]+$/,''),c=body.split(',').map(x=>x.trim().split(/\s+/).map(w=>/^\d+[a-z]?$/i.test(w)?w.toUpperCase():w.charAt(0).toUpperCase()+w.slice(1).toLowerCase()).join(' ')).filter(Boolean).join(', ');return[c,p].filter(Boolean).join(', ');};
function epcRows(h,postcode){const rows=[],seen=new Set(),re=/<a\b([^>]*href=["']([^"']*\/energy-certificate\/[^"']+)["'][^>]*)>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(String(h||'')))){const href=m[2],address=title(m[3]);if(href&&address&&!seen.has(href)){seen.add(href);rows.push({href,address,postcode})}}return rows;}
async function epcPage(postcode){const p=pc(postcode);if(!p)return[];return epcRows(await text(`https://find-energy-certificate.service.gov.uk/find-a-certificate/search-by-postcode?postcode=${encodeURIComponent(p)}`,1800),p);}
async function geo(p,limit=8){const u=new URL('https://nominatim.openstreetmap.org/search');for(const[k,v]of Object.entries({format:'jsonv2',addressdetails:'1',countrycodes:'gb',limit:String(limit)}))u.searchParams.set(k,v);if(p.houseNumber&&p.road){u.searchParams.set('street',`${p.houseNumber} ${p.road}`);if(p.locality)u.searchParams.set('city',p.locality);if(p.postcode)u.searchParams.set('postalcode',p.postcode);}else u.searchParams.set('q',p.clean);const d=await json(u.toString(),900);return Array.isArray(d)?d:[];}
export async function addressQuick(q,limit=8,autocomplete=false){const p=parse(q);if(p.clean.length<3)return{ok:true,rows:[]};const [g,e]=await Promise.all([timed(geo(p,limit).catch(()=>[]),autocomplete?900:1400,[]),!autocomplete&&p.postcode?timed(epcPage(p.postcode).catch(()=>[]),1400,[]):Promise.resolve([])]),rows=[],wanted=String(p.lookupNumber||'').toUpperCase();for(const x of e){if(wanted&&!nums(x.address).has(wanted))continue;if(p.road&&!sameRoad(x.address,p.road))continue;const best=g.find(z=>pc(z?.address?.postcode||'')===p.postcode)||g[0];rows.push({lat:Number(best?.lat)||0,lon:Number(best?.lon)||0,display_name:x.address,address:{...(best?.address||{}),house_number:p.lookupNumber||'',road:p.road||best?.address?.road||'',postcode:p.postcode},importance:1,_exactDisplay:x.address,_exactEpcHref:x.href,_score:300,_needsPreciseGeocode:!best});if(rows.length>=limit)break;}for(const x of g){if(rows.some(r=>String(r.display_name).toLowerCase()===String(x.display_name||'').toLowerCase()))continue;rows.push({lat:Number(x.lat),lon:Number(x.lon),display_name:String(x.display_name||''),address:x.address||{},importance:Number(x.importance)||0,_score:120});if(rows.length>=limit)break;}return{ok:true,rows:rows.slice(0,limit),postcode:p.postcode};}
function detail(h){const body=clean(h),field=label=>{const r=new RegExp(`<dt[^>]*>\\s*${label}\\s*<\\/dt>\\s*<dd[^>]*>([\\s\\S]*?)<\\/dd>`,'i');return clean(String(h||'').match(r)?.[1]||'');},sqm=Number((field('Total\\s+floor\\s+area')||body.match(/total\s+floor\s+area.{0,80}?([\d,.]+)/i)?.[0]||'').match(/([\d,.]+)/)?.[1]?.replace(/,/g,'')),rating=(field('Current\\s+energy(?:\\s+efficiency)?\\s+rating').match(/\b([A-G])\b/i)?.[1]||body.slice(0,2800).match(/(?:current\s+energy(?:\s+efficiency)?\s+rating\s*(?:is|:)?|energy\s+rating\s*)([A-G])\b/i)?.[1]||'').toUpperCase(),rooms=parseInt(field('Number\\s+of\\s+habitable\\s+rooms')||field('Habitable\\s+rooms'),10);return{currentEnergyRating:rating,sqm:Number.isFinite(sqm)?sqm:null,sqft:Number.isFinite(sqm)?Math.round(sqm*10.7639):null,propertyType:field('Property\\s+type'),builtForm:field('Built\\s+form'),tenure:field('Tenure'),habitableRooms:Number.isFinite(rooms)?rooms:null};}
export async function subjectEpc(address,postcode){const p=parse(address),P=pc(postcode||p.postcode);if(!P)return{ok:true,found:false};let rows=await timed(epcPage(P).catch(()=>[]),1600,[]),wanted=String(p.lookupNumber||'').toUpperCase(),c=rows.filter(r=>(!wanted||nums(r.address).has(wanted))&&(!p.road||sameRoad(r.address,p.road)));if(!c.length&&wanted)c=rows.filter(r=>nums(r.address).has(wanted));if(c.length!==1)return{ok:true,found:false,candidates:c.length};const cert=new URL(c[0].href,'https://find-energy-certificate.service.gov.uk').toString(),d=await timed(text(cert,3600).then(detail).catch(()=>null),1700,null);return{ok:true,found:true,address:c[0].address,certificateUrl:cert,...(d||{})};}
function assigned(src,mark){const mi=src.indexOf(mark);if(mi<0)return null;const eq=src.indexOf('=',mi+mark.length),st=src.indexOf('{',eq);if(eq<0||st<0)return null;let d=0,s=false,e=false;for(let i=st;i<src.length;i++){const c=src[i];if(s){if(e)e=false;else if(c==='\\')e=true;else if(c==='"')s=false;continue}if(c==='"'){s=true;continue}if(c==='{')d++;else if(c==='}'&&!--d){try{return JSON.parse(src.slice(st,i+1))}catch{return null}}}return null;}
function flat(data){let a=data;if(typeof a==='string'){try{a=JSON.parse(a)}catch{return null}}if(!Array.isArray(a)||!a.length)return null;const C=new Map();function f(i){if(!Number.isInteger(i))return i;if(i<0||i>=a.length)return undefined;if(C.has(i))return C.get(i);const r=a[i];if(r===null||typeof r!=='object'){C.set(i,r);return r}if(Array.isArray(r)){const x=[];C.set(i,x);for(const q of r)x.push(Number.isInteger(q)?f(q):q);return x}const o={};C.set(i,o);for(const[k,v]of Object.entries(r))o[k]=Number.isInteger(v)?f(v):v;return o}return f(0)}
const model=h=>{let m=null;if(h.includes('window.__PAGE_MODEL')){const p=assigned(h,'window.__PAGE_MODEL');if(p)m=flat(p.data)}if(!m?.propertyData&&h.includes('window.PAGE_MODEL'))m=assigned(h,'window.PAGE_MODEL');return m?.propertyData?m:null;};
const size=pd=>{const s=Array.isArray(pd?.sizings)?pd.sizings:[],ft=s.find(x=>String(x?.unit||'').toLowerCase()==='sqft'),mt=s.find(x=>['sqm','sq m','m2','m²'].includes(String(x?.unit||'').toLowerCase())),a=Number(ft?.minimumSize??ft?.min??ft?.maximumSize??ft?.max),b=Number(mt?.minimumSize??mt?.min??mt?.maximumSize??mt?.max);return Number.isFinite(a)&&a>100?Math.round(a):Number.isFinite(b)&&b>10?Math.round(b*10.7639):null;};
const group=v=>{const s=String(v||'').toLowerCase();if(/flat|apartment|maisonette/.test(s))return'flat';if(/semi/.test(s))return'semi';if(/terrace/.test(s))return'terrace';if(/detached/.test(s))return'detached';if(/bungalow/.test(s))return'bungalow';return'';};
const path=p=>(String(p||'').toUpperCase().replace(/[^A-Z0-9]/g,'').match(/.{1,2}/g)||[]).join('/');
async function loc(postcode){const d=await json(`https://www.rightmove.co.uk/typeAhead/uknostreet/${path(postcode)}/`,1200),rows=d?.typeAheadLocations||[],P=String(postcode).replace(/\s+/g,'').toUpperCase(),x=rows.find(r=>/^POSTCODE\^/i.test(String(r?.locationIdentifier||''))&&String(r?.displayName||'').replace(/\s+/g,'').toUpperCase().includes(P))||rows.find(r=>/^POSTCODE\^/i.test(String(r?.locationIdentifier||'')));return String(x?.locationIdentifier||'');}
async function search(id,radius){const u=new URL('https://www.rightmove.co.uk/api/_search');for(const[k,v]of Object.entries({locationIdentifier:id,numberOfPropertiesPerPage:'48',radius:String(radius),sortType:'6',index:'0',includeSSTC:'true',viewType:'LIST',channel:'BUY',areaSizeUnit:'sqft',currencyCode:'GBP',isFetching:'false'}))u.searchParams.set(k,v);const d=await json(u.toString(),240);return Array.isArray(d?.properties)?d.properties:[];}
async function facts(id){try{return await timed(text(`https://www.rightmove.co.uk/properties/${id}`,600).then(h=>{const p=model(h)||{};return{sqft:size(p),bedrooms:Number(p?.bedrooms)||null,bathrooms:Number(p?.bathrooms)||null,propertyType:String(p?.propertySubType||p?.propertyTypeFullDescription||p?.propertyType||'')}}),1700,{})}catch{return{}}}
const dist=(a,b,c,d)=>{if(![a,b,c,d].every(Number.isFinite))return null;const R=6371000,r=x=>x*Math.PI/180,p1=r(a),p2=r(c),dp=r(c-a),dl=r(d-b),h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(h),Math.sqrt(1-h));};
export async function marketComps(params){const P=pc(params.get('postcode')||'');if(!P)return{ok:true,rows:[]};const L=await timed(loc(P).catch(()=>''),1400,'');if(!L)return{ok:true,rows:[]};const [exact,near]=await Promise.all([timed(search(L,0).catch(()=>[]),1700,[]),timed(search(L,1).catch(()=>[]),1900,[])]),seen=new Set(),sqft=Number(params.get('sqft'))||null,beds=Number(params.get('beds'))||null,tg=group(params.get('type')),R=road(params.get('road')),lat=Number(params.get('lat')),lon=Number(params.get('lon'));let rows=[];for(const x of [...exact,...near]){const id=String(x?.id||x?.propertyId||'');if(!id||seen.has(id))continue;seen.add(id);const l=x?.location||{},address=String(x?.displayAddress||x?.address?.displayAddress||x?.address||''),price=money(x?.price?.amount||x?.price?.value||x?.price);if(!price)continue;const row={id,address,price,bedrooms:Number(x?.bedrooms)||null,bathrooms:Number(x?.bathrooms)||null,propertyType:String(x?.propertySubType||x?.propertyTypeFullDescription||x?.propertyType||''),lat:Number(l.latitude??x?.latitude)||null,lon:Number(l.longitude??x?.longitude)||null,url:`https://www.rightmove.co.uk/properties/${id}`,status:String(x?.displayStatus||x?.status||x?.statusText||''),sqft:null};let s=0;if(R&&road(address).includes(R))s+=150;if(address.toUpperCase().replace(/\s+/g,'').includes(P.replace(/\s+/g,'')))s+=100;if(tg&&group(row.propertyType)===tg)s+=75;else if(tg&&group(row.propertyType))s-=55;if(beds&&row.bedrooms)s+=Math.max(-80,65-Math.abs(beds-row.bedrooms)*38);row.distance=dist(lat,lon,row.lat,row.lon);if(Number.isFinite(row.distance))s+=Math.max(0,90-row.distance/18);row._score=s;rows.push(row)}rows.sort((a,b)=>b._score-a._score);const top=rows.slice(0,10),D=await Promise.all(top.map(r=>facts(r.id)));for(let i=0;i<top.length;i++){Object.assign(top[i],D[i]);if(sqft&&top[i].sqft){const ratio=Math.min(sqft,top[i].sqft)/Math.max(sqft,top[i].sqft);top[i]._score+=ratio*130}}rows.sort((a,b)=>b._score-a._score);return{ok:true,rows:rows.slice(0,14)}}
