// v3 presentation layer for inferred profile and richer comparable cards.
(() => {
  renderFacts=function(manual,epc,subject,listing,estimate){
    const facts=[],add=(label,value,extra='',cls='')=>{if(value!==null&&value!==undefined&&String(value)!=='')facts.push(`<div class="fact ${cls}"><span>${escapeHtml(label)}</span><strong>${escapeHtml(value)}</strong>${extra}</div>`);},address=listing?.exactAddress||displayName(manual)||listing?.displayAddress;$('propertyAddress').textContent=address||'Property';const link=$('sourceLink');if(listing?.url){link.href=listing.url;link.classList.remove('hidden');}else link.classList.add('hidden');
    const type=estimate?.propertyType||typeLabel(subject?.best?.propertyType||listing?.propertyType||epc?.builtForm||epc?.propertyType)||'Unknown',profile=estimate?{bedrooms:estimate.subjectBedrooms,bedroomsEstimated:estimate.bedroomsEstimated,bathrooms:estimate.subjectBathrooms,bathroomsEstimated:estimate.bathroomsEstimated,sqft:estimate.subjectSqft}:inferPropertyProfile(epc,listing,type,[]),sqft=Number(listing?.squareFootage?.sqft||epc?.sqft||profile.sqft);
    add('Postcode',manualPostcode(manual)||listing?.postcode||'');add('Property type',type);add('Floor area',sqft>0?`${Math.round(sqft).toLocaleString('en-GB')} sq ft`:(epc?._loading?'Checking…':'Not found'));if(profile.bedrooms)add('Bedrooms',`${profile.bedrooms}${profile.bedroomsEstimated?' likely':''}`,'',profile.bedroomsEstimated?'estimated':'');if(profile.bathrooms)add('Bathrooms',`${profile.bathrooms}${profile.bathroomsEstimated?' likely':''}`,'',profile.bathroomsEstimated?'estimated':'');
    const rating=String(epc?.currentEnergyRating||listing?.epcRating||'').toUpperCase().match(/\b([A-G])\b/)?.[1]||'',epcText=rating?`EPC rating ${rating}`:(epc?._loading?'Checking…':'Not found'),epcUrl=String(epc?.certificateUrl||listing?.epcUrl||'');add('EPC',epcText,epcUrl?`<a class="fact-link" target="_blank" rel="noopener" href="${escapeHtml(epcUrl)}">Open EPC</a>`:'');add('Tenure',epc?.tenure||uriTail(subject?.best?.estateType)||'');
    if(listing?.askingPrice){add('Current asking price',money(listing.askingPrice));if(sqft>0)add('Price per sq ft',`£${Math.round(Number(listing.askingPrice)/sqft).toLocaleString('en-GB')} / sq ft`);}
    else if(estimate?.reliable&&Number(estimate.midpoint)>0&&sqft>0)add('Estimated price per sq ft',`£${Math.round(Number(estimate.midpoint)/sqft).toLocaleString('en-GB')} / sq ft`);
    if(subject?.history?.[0])add('Last registered sale',`${money(subject.history[0].amount)} · ${dateShort(subject.history[0].date)}`);$('facts').innerHTML=facts.join('');
    const meta=$('profileMeta');if(meta){const bits=[];if(profile.bedrooms)bits.push(`${profile.bedrooms} bed${profile.bedroomsEstimated?' likely':''}`);if(profile.bathrooms)bits.push(`${profile.bathrooms} bath${profile.bathroomsEstimated?' likely':''}`);if(sqft)bits.push(`${Math.round(sqft).toLocaleString('en-GB')} sq ft`);if(listing?.askingPrice&&sqft>0)bits.push(`£${Math.round(Number(listing.askingPrice)/sqft).toLocaleString('en-GB')}/sq ft`);if(rating)bits.push(`EPC ${rating}`);meta.textContent=bits.join(' · ');}
  };

  renderEstimate=function(estimate){$('estimateMid').textContent=estimate?.reliable?money(estimate.midpoint):'Not enough evidence';$('estimateRange').textContent=estimate?.reliable?`${money(estimate.low)} – ${money(estimate.high)}`:'More evidence is still being gathered.';const conf=estimate?.confidence||'Low';$('confidence').textContent=conf==='Refining'?'Refining estimate':`${conf} confidence`;$('confidence').className=`confidence ${String(conf).toLowerCase()}`;$('explanation').innerHTML=estimate?.reliable?`<p>${escapeHtml(estimate.method)}.</p><p>The model prioritises same-street/same-postcode evidence, then property type, floor area and recency. Current Rightmove listings are a market cross-check rather than sold prices.</p>`:`<p>There is not yet enough matched evidence for a sensible estimate.</p>`;};

  renderComparables=function(estimate){
    const rows=estimate?.comps||[];$('compCount').textContent=rows.length?`${rows.length} strongest matches`:'';$('comparables').innerHTML=rows.length?rows.map((r,i)=>{const sameStreet=normaliseRoad(r.street)===normaliseRoad(state.selected?.address?.road||parseAddressQuery(displayName(state.selected||{})).road),badges=[sameStreet?'Same street':'',r.postcode===manualPostcode(state.selected||{})?'Same postcode':'',r.sqft?`${Math.round(r.sqft).toLocaleString('en-GB')} sq ft`:''].filter(Boolean);return `<div class="comp comp-rich"><div class="comp-main"><div class="comp-rank">${i+1}</div><div><strong>${escapeHtml(lrAddress(r))}</strong><span>${escapeHtml(dateShort(r.date))} · ${escapeHtml(typeLabel(r.propertyType)||'Property')}</span><div class="comp-badges">${badges.map(b=>`<em>${escapeHtml(b)}</em>`).join('')}</div></div></div><div class="comp-money"><strong>${escapeHtml(money(r.amount))}</strong>${r.sizeAdjusted?`<span>Size-adjusted ${escapeHtml(money(roundEstimate(r.implied)))}</span>`:''}</div></div>`;}).join(''):`<p class="muted">No suitable recent sold comparables found.</p>`;
    const market=estimate?.marketListings||[],card=$('marketCard');if(market.length){card.classList.remove('hidden');$('marketListings').innerHTML=market.map((r,i)=>{const status=r.status||'For sale',size=r.sqft?`${Math.round(r.sqft).toLocaleString('en-GB')} sq ft`:'';return `<a class="comp market comp-rich" href="${escapeHtml(r.url)}" target="_blank" rel="noopener"><div class="comp-main"><div class="comp-rank">${i+1}</div><div><strong>${escapeHtml(r.address||'Rightmove listing')}</strong><span>${[r.bedrooms?`${r.bedrooms} bed`:'',r.bathrooms?`${r.bathrooms} bath`:'',size,r.propertyType].filter(Boolean).map(escapeHtml).join(' · ')}</span><div class="comp-badges">${r.isSubject?'<em>Subject listing</em>':''}<em class="status">${escapeHtml(status)}</em>${Number.isFinite(r.distance)?`<em>${Math.round(r.distance)} m</em>`:''}</div></div></div><div class="comp-money"><strong>${escapeHtml(money(r.price))}</strong><span>Rightmove</span></div></a>`;}).join('');const ms=$('marketSummary');if(ms)ms.textContent=`${market.length} live / SSTC matches ranked by location, type, beds and size`;}else card.classList.add('hidden');
  };
})();