import oldWorker from './_worker.js';

function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});}
function text(v){return String(v||'').replace(/<script\b[\s\S]*?<\/script>/gi,' ').replace(/<style\b[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;|&#34;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&pound;|&#163;/gi,'£').replace(/\s+/g,' ').trim();}
function money(v){if(typeof v==='number'&&Number.isFinite(v))return v;const m=String(v||'').replace(/,/g,'').match(/(\d+(?:\.\d+)?)/);return m?Number(m[1]):null;}
function postcode(v){const c=String(v||'').toUpperCase().replace(/\s+/g,'');const m=c.match(/^([A-Z]{1,2}\d[A-Z\d]?)(\d[A-Z]{2})$/);return m?`${m[1]} ${m[2]}`:'';}
function assigned(src,marker){const mi=src.indexOf(marker);if(mi<0)return null;const eq=src.indexOf('=',mi+marker.length),start=src.indexOf('{',eq);if(eq<0||start<0)return null;let d=0,s=false,e=false;for(let i=start;i<src.length;i++){const c=src[i];if(s){if(e)e=false;else if(c==='\\')e=true;else if(c==='"')s=false;continue;}if(c==='"'){s=true;continue;}if(c==='{')d++;else if(c==='}'&&!--d){try{return JSON.parse(src.slice(start,i+1));}catch{return null;}}}return null;}
function flattened(data){let a=data;if(typeof a==='string'){try{a=JSON.parse(a);}catch{return null;}}if(!Array.isArray(a)||!a.length)return null;const cache=new Map();function d(i){if(!Number.isInteger(i))return i;if(i<0){if(i===-3)return NaN;if(i===-4)return Infinity;if(i===-5)return-Infinity;if(i===-6)return-0;return undefined;}if(i>=a.length)return undefined;if(cache.has(i))return cache.get(i);const r=a[i];if(r===null||typeof r!=='object'){cache.set(i,r);return r;}if(Array.isArray(r)){const x=[];cache.set(i,x);for(const q of r)x.push(Number.isInteger(q)?d(q):q);return x;}const o={};cache.set(i,o);for(const[k,v]of Object.entries(r))o[k]=Number.isInteger(v)?d(v):v;return o;}try{return d(0);}catch{return null;}}
function model(html){let m=null;if(html.includes('window.__PAGE_MODEL')){const p=assigned(html,'window.__PAGE_MODEL');if(p)m=flattened(p.data);}if(!m?.propertyData&&html.includes('window.PAGE_MODEL'))m=assigned(html,'window.PAGE_MODEL');return m?.propertyData?m:null;}
function size(pd){const s=Array.isArray(pd?.sizings)?pd.sizings:[],ft=s.find(x=>String(x?.unit||'').toLowerCase()==='sqft'),mt=s.find(x=>['sqm','sq m','m2','m²'].includes(String(x?.unit||'').toLowerCase())),sqft=Number(ft?.minimumSize??ft?.min??ft?.maximumSize??ft?.max),sqm=Number(mt?.minimumSize??mt?.min??mt?.maximumSize??mt?.max);if(Number.isFinite(sqft)&&sqft>=150&&sqft<=30000)return{sqft:Math.round(sqft),sqm:Number.isFinite(sqm)?Math.round(sqm*10)/10:Math.round(sqft/10.7639*10)/10,source:'Rightmove size'};if(Number.isFinite(sqm)&&sqm>=14&&sqm<=3000)return{sqft:Math.round(sqm*10.7639),sqm:Math.round(sqm*10)/10,source:'Rightmove size'};const p=money(pd?.prices?.primaryPrice),pp=money(pd?.prices?.pricePerSqFt);if(p&&pp){const n=p/pp;if(n>=150&&n<=30000)return{sqft:Math.round(n),sqm:Math.round(n/10.7639*10)/10,source:'Rightmove price per sq ft'};}return null;}
function epc(html){const raw=String(html||''),lead=text(raw.slice(0,250000));return(lead.match(/this property[’']?s (?:current )?energy(?: efficiency)? rating is ([A-G])\b/i)?.[1]||lead.match(/current energy(?: efficiency)? rating.{0,50}?\b([A-G])\b/i)?.[1]||lead.match(/\bEPC\s*(?:rating)?\s*[:\-]?\s*([A-G])\b/i)?.[1]||raw.match(/(?:epcRating|energyRating|currentEnergyRating|currentEnergyEfficiencyBand|energyEfficiencyBand)[^A-G]{0,60}["']?([A-G])["']?/i)?.[1]||'').toUpperCase();}
function ids(html,pd){let deliveryPointId=Number(pd?.address?.deliveryPointId??pd?.deliveryPointId)||null,pc=postcode(pd?.address?.outcode&&pd?.address?.incode?`${pd.address.outcode} ${pd.address.incode}`:'');if(!pc){const out=html.match(/(?:"|\\")outcode(?:"|\\")\s*:\s*(?:"|\\")([A-Z0-9]+)(?:"|\\")/i)?.[1]||'',inc=html.match(/(?:"|\\")incode(?:"|\\")\s*:\s*(?:"|\\")([A-Z0-9]+)(?:"|\\")/i)?.[1]||'';pc=postcode(out&&inc?`${out} ${inc}`:'');}return{deliveryPointId,postcode:pc};}
async function upstream(url,accept='text/html,application/xhtml+xml,*/*;q=0.8',ttl=120){const cache=await caches.open('property-tool-v2');const key=new Request(url,{headers:{accept}}),hit=await cache.match(key);if(hit)return hit;const r=await fetch(url,{headers:{Accept:accept,'Accept-Language':'en-GB,en;q=0.9','User-Agent':'Mozilla/5.0 (compatible; PropertyTool/2.0)'}});if(!r.ok)throw new Error(`Upstream request failed (${r.status})`);const h=new Headers(r.headers);h.set('Cache-Control',`public, max-age=${ttl}`);const out=new Response(r.body,{status:r.status,headers:h});if(ttl)await cache.put(key,out.clone());return out;}
async function fastRightmove(raw){const id=String(raw||'').match(/rightmove\.co\.uk\/properties\/(\d+)/i)?.[1]||'';if(!id)throw new Error('Paste a Rightmove property link.');const url=`https://www.rightmove.co.uk/properties/${id}`,html=await(await upstream(url)).text(),m=model(html),pd=m?.propertyData||{},loc=pd?.location||{},i=ids(html,pd),displayAddress=String(pd?.address?.displayAddress||text(html.match(/<h1\b[^>]*>([\s\S]*?)<\/h1>/i)?.[1])||`Rightmove property ${id}`).trim(),askingPrice=money(pd?.prices?.primaryPrice)||money(text(html).match(/£\s*[\d,]{5,}/)?.[0]);return{ok:true,propertyId:id,url,displayAddress,exactAddress:'',exactSource:'',postcode:i.postcode,deliveryPointId:i.deliveryPointId,lat:Number.isFinite(Number(loc.latitude))?Number(loc.latitude):null,lon:Number.isFinite(Number(loc.longitude))?Number(loc.longitude):null,askingPrice:Number.isFinite(Number(askingPrice))?Number(askingPrice):null,squareFootage:size(pd),bedrooms:Number(pd?.bedrooms)||null,bathrooms:Number(pd?.bathrooms)||null,propertyType:String(pd?.propertySubType||pd?.propertyTypeFullDescription||pd?.propertyType||''),epcRating:epc(html),epcUrl:''};}
async function planningProxy(u){let target;try{target=new URL(u.searchParams.get('url')||'');}catch{return json({error:'Invalid URL.'},400);}if(target.protocol!=='https:'||target.hostname!=='www.planning.data.gov.uk')return null;try{const r=await upstream(target.toString(),u.searchParams.get('accept')||'application/json,*/*;q=0.8',120),h=new Headers();h.set('content-type',r.headers.get('content-type')||'application/json; charset=utf-8');h.set('cache-control','public, max-age=120');return new Response(r.body,{status:r.status,headers:h});}catch(e){return json({error:String(e?.message||'Planning lookup failed.')},502);}}

export default {
  async fetch(request,env,ctx){
    const u=new URL(request.url);
    if(u.pathname==='/api/rightmove'){
      try{return json(await fastRightmove(u.searchParams.get('url')||''));}catch(e){return json({ok:false,error:String(e?.message||'Could not read Rightmove listing.')},502);}
    }
    if(u.pathname==='/api/rightmove-address'){
      const slow=new URL(request.url);slow.pathname='/api/rightmove';
      return oldWorker.fetch(new Request(slow.toString(),request),env,ctx);
    }
    if(u.pathname==='/api/proxy'){
      const p=await planningProxy(u);if(p)return p;
    }
    return oldWorker.fetch(request,env,ctx);
  }
};
